format = """
[](fg:#8e8eff)\
$os\
[](fg:#8e8eff bg:#8e8eff)\
$directory\
[](fg:#8f4bb4 bg:#b082ca)\
$git_branch\
$git_status\
[](fg:#b082ca)\
$conda\
$python\
$nodejs\
$rust\
$golang\
$php\
[](fg:#faadee)\
$time\
[ ](fg:#faadee)\
\n$character"""

[os]
format = "[$symbol]($style)"
style = "fg:#e3e5e5 bg:#8e8eff"
disabled = false

[directory]
style = "fg:#e3e5e5 bg:#8f4bb4"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
format = '[[ $symbol $branch ](fg:#e3e5e5 bg:#b082ca)]($style)'

[git_status]
format = '[[($all_status$ahead_behind )](fg:#e3e5e5 bg:#b082ca)]($style)'

[conda]
symbol = "◯ "
format = "[ $symbol$environment ]($style)"
ignore_base = false

[python]
format = "[ ${symbol}${version} ]($style)"
symbol = "[⌉](bold bright-blue)⌊ "
version_format = "${raw}"
style = "bold bright-yellow"

[nodejs]
symbol = ""
format = '[[ $symbol ($version) ](fg:#b082ca bg:#212736)]($style)'

[rust]
symbol = ""
format = '[[ $symbol ($version) ](fg:#b082ca bg:#212736)]($style)'

[golang]
symbol = ""
format = '[[ $symbol ($version) ](fg:#b082ca bg:#212736)]($style)'

[php]
symbol = ""
format = '[[ $symbol ($version) ](fg:#b082ca bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[[  $time ](fg:#212736 bg:#faadee)]($style)'
